### PR TITLE
switch the "Test Application" from creating/signing with DSA to RSA PKCS1 with SHA256

### PR DESCRIPTION
**Pull request by richard-bt**
I was getting compiler errors having to do with these icons. I've just removed usage of icons as they don't seem relevant to update functionality.

### CODE REVIEW

**Comment by richard-bt** [comment]
@angitbit This branch removes some code having to do with icons so I can build the "SparkleDotNET Tools" application.

**Comment by richard-bt** [comment]
Notice that the target of this pull request is your `anbuild` branch - if this pull request is merged the changes will become a part of your original pull request: https://github.com/bt-browser/SparkleDotNET/pull/2

**Comment by angitbit** [comment]
I don't have this issue; are you on vs 2013 update 4?

**Comment by richard-bt** [comment]
Yes, I am on VS 2013 update 4.

**Comment by richard-bt** [comment]
For what it's worth, I _think_ I was only getting these icon issues when trying to build the "SparkleDotNET Tools" executable.

**Comment by angitbit** [comment]
is this your tip? e579022bf46a3e1bb0930f4e707b6a7ac83a843c
- Merge pull request #2 from a2h/master

Don't use System.Management for system profiling

**Comment by richard-bt** [comment]
I don't think that's my tip? I'm not sure what you're asking from me.

My branch `anbuild_richardfixes` is currently at ac3074e3b8a99833f29c4ea39c1b9e504c48aee2, which I branched from your commit d736949d6c5c34fe5d210d232e493e8e29a192b3. 

When I attempted to build your `anbuild` branch at d736949d6c5c34fe5d210d232e493e8e29a192b3 I get these errors: (I'll leave an additional comment with screenshot/text of my error next)

**Comment by richard-bt** [comment]
Screenshot of error: http://screencast.com/t/6YTcuHbnIocw

```
Warning 1   Possible unintended reference comparison; to get a value comparison, cast the left hand side to type 'string'   D:\bt\KNFoundation\KNFoundation\KNKVC\Bindings\KNBinding.cs 112 67  KNFoundation

Warning 2   Possible unintended reference comparison; to get a value comparison, cast the left hand side to type 'string'   D:\bt\KNFoundation\KNFoundation\KNKVC\Bindings\KNBinding.cs 162 73  KNFoundation

Error   3   Metadata file 'D:\bt\SparkleDotNET\SparkleDotNET\bin\Debug\SparkleDotNET.dll' could not be found    D:\bt\SparkleDotNET\SparkleDotNET Test Application\CSC  SparkleDotNET Tools

Error   4   'KNFoundation.KNBundle' does not contain a definition for 'BundleIcon' and no extension method 'BundleIcon' accepting a first argument of type 'KNFoundation.KNBundle' could be found (are you missing a using directive or an assembly reference?) D:\bt\SparkleDotNET\SparkleDotNET\SUHost.cs 55  31  SparkleDotNET

Error   5   'KNFoundation.KNBundle' does not contain a definition for 'LargeBundleIcon' and no extension method 'LargeBundleIcon' accepting a first argument of type 'KNFoundation.KNBundle' could be found (are you missing a using directive or an assembly reference?)   D:\bt\SparkleDotNET\SparkleDotNET\SUHost.cs 61  31  SparkleDotNET
```

**Comment by richard-bt** [comment]
Getting "SparkleDotNET Tools" solution/application to build wasn't entirely intuitive - it doesn't seem like the SLN is quite right because I had to rebuild projects by hand in some order (roughly lowest dependency to highest dependency) for the "SparkleDotNET Tools" solution to build.

**Comment by angitbit** [comment]
sorry, forgot I backdated knfoundation to https://github.com/iKenndac/KNFoundation/commit/156c58a7066c62e23a2638805317c9ed2ec68775

**Comment by richard-bt** [comment]
When I backdate KNFoundation to that commit, I get even more errors when trying to build :(

```
Warning 1   Possible unintended reference comparison; to get a value comparison, cast the left hand side to type 'string'   D:\bt\KNFoundation\KNFoundation\KNKVC\Bindings\KNBinding.cs 112 67  KNFoundation
Warning 2   Possible unintended reference comparison; to get a value comparison, cast the left hand side to type 'string'   D:\bt\KNFoundation\KNFoundation\KNKVC\Bindings\KNBinding.cs 162 73  KNFoundation
Error   3   The type or namespace name 'KNFoundation' could not be found (are you missing a using directive or an assembly reference?)  D:\bt\SparkleDotNET\SparkleDotNET Test Application\MainWindow.xaml.cs   19  7   SparkleDotNET Tools
Error   4   The type or namespace name 'KNFoundation' could not be found (are you missing a using directive or an assembly reference?)  D:\bt\SparkleDotNET\SparkleDotNET Test Application\MainWindow.xaml.cs   20  7   SparkleDotNET Tools
Error   5   The type or namespace name 'KNKVOObserver' could not be found (are you missing a using directive or an assembly reference?) D:\bt\SparkleDotNET\SparkleDotNET Test Application\MainWindow.xaml.cs   27  47  SparkleDotNET Tools
Warning 6   Could not resolve this reference. Could not locate the assembly "KNFoundation". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. SparkleDotNET Tools
Warning 7   The referenced component 'KNFoundation' could not be found.     SparkleDotNET Tools
Error   8   The type or namespace name 'KNFoundation' could not be found (are you missing a using directive or an assembly reference?)  D:\bt\SparkleDotNET\SparkleDotNET Test Application\UpdateSigningKey.cs  6   7   SparkleDotNET Tools
Error   9   'System.Collections.Generic.Dictionary<string,object>' does not contain a definition for 'ValueForKey' and no extension method 'ValueForKey' accepting a first argument of type 'System.Collections.Generic.Dictionary<string,object>' could be found (are you missing a using directive or an assembly reference?) D:\bt\SparkleDotNET\SparkleDotNET Test Application\UpdateSigningKey.cs  17  37  SparkleDotNET Tools
Error   10  'System.Collections.Generic.Dictionary<string,object>' does not contain a definition for 'ValueForKey' and no extension method 'ValueForKey' accepting a first argument of type 'System.Collections.Generic.Dictionary<string,object>' could be found (are you missing a using directive or an assembly reference?) D:\bt\SparkleDotNET\SparkleDotNET Test Application\UpdateSigningKey.cs  18  67  SparkleDotNET Tools
Error   11  'System.Collections.Generic.Dictionary<string,object>' does not contain a definition for 'ValueForKey' and no extension method 'ValueForKey' accepting a first argument of type 'System.Collections.Generic.Dictionary<string,object>' could be found (are you missing a using directive or an assembly reference?) D:\bt\SparkleDotNET\SparkleDotNET Test Application\UpdateSigningKey.cs  19  68  SparkleDotNET Tools
Error   12  'SparkleDotNET_Test_Application.UpdateSigningKey' does not contain a definition for 'WillChangeValueForKey' and no extension method 'WillChangeValueForKey' accepting a first argument of type 'SparkleDotNET_Test_Application.UpdateSigningKey' could be found (are you missing a using directive or an assembly reference?)   D:\bt\SparkleDotNET\SparkleDotNET Test Application\UpdateSigningKey.cs  34  22  SparkleDotNET Tools
Error   13  'SparkleDotNET_Test_Application.UpdateSigningKey' does not contain a definition for 'DidChangeValueForKey' and no extension method 'DidChangeValueForKey' accepting a first argument of type 'SparkleDotNET_Test_Application.UpdateSigningKey' could be found (are you missing a using directive or an assembly reference?) D:\bt\SparkleDotNET\SparkleDotNET Test Application\UpdateSigningKey.cs  36  22  SparkleDotNET Tools
Error   14  'SparkleDotNET_Test_Application.UpdateSigningKey' does not contain a definition for 'WillChangeValueForKey' and no extension method 'WillChangeValueForKey' accepting a first argument of type 'SparkleDotNET_Test_Application.UpdateSigningKey' could be found (are you missing a using directive or an assembly reference?)   D:\bt\SparkleDotNET\SparkleDotNET Test Application\UpdateSigningKey.cs  43  22  SparkleDotNET Tools
Error   15  'SparkleDotNET_Test_Application.UpdateSigningKey' does not contain a definition for 'DidChangeValueForKey' and no extension method 'DidChangeValueForKey' accepting a first argument of type 'SparkleDotNET_Test_Application.UpdateSigningKey' could be found (are you missing a using directive or an assembly reference?) D:\bt\SparkleDotNET\SparkleDotNET Test Application\UpdateSigningKey.cs  45  22  SparkleDotNET Tools
Error   16  'SparkleDotNET_Test_Application.UpdateSigningKey' does not contain a definition for 'WillChangeValueForKey' and no extension method 'WillChangeValueForKey' accepting a first argument of type 'SparkleDotNET_Test_Application.UpdateSigningKey' could be found (are you missing a using directive or an assembly reference?)   D:\bt\SparkleDotNET\SparkleDotNET Test Application\UpdateSigningKey.cs  52  22  SparkleDotNET Tools
Error   17  'SparkleDotNET_Test_Application.UpdateSigningKey' does not contain a definition for 'DidChangeValueForKey' and no extension method 'DidChangeValueForKey' accepting a first argument of type 'SparkleDotNET_Test_Application.UpdateSigningKey' could be found (are you missing a using directive or an assembly reference?) D:\bt\SparkleDotNET\SparkleDotNET Test Application\UpdateSigningKey.cs  54  22  SparkleDotNET Tools
Error   18  'System.Collections.Generic.Dictionary<string,object>' does not contain a definition for 'SetValueForKey' and no extension method 'SetValueForKey' accepting a first argument of type 'System.Collections.Generic.Dictionary<string,object>' could be found (are you missing a using directive or an assembly reference?)   D:\bt\SparkleDotNET\SparkleDotNET Test Application\UpdateSigningKey.cs  62  18  SparkleDotNET Tools
Error   19  'System.Collections.Generic.Dictionary<string,object>' does not contain a definition for 'SetValueForKey' and no extension method 'SetValueForKey' accepting a first argument of type 'System.Collections.Generic.Dictionary<string,object>' could be found (are you missing a using directive or an assembly reference?)   D:\bt\SparkleDotNET\SparkleDotNET Test Application\UpdateSigningKey.cs  63  18  SparkleDotNET Tools
Error   20  'System.Collections.Generic.Dictionary<string,object>' does not contain a definition for 'SetValueForKey' and no extension method 'SetValueForKey' accepting a first argument of type 'System.Collections.Generic.Dictionary<string,object>' could be found (are you missing a using directive or an assembly reference?)   D:\bt\SparkleDotNET\SparkleDotNET Test Application\UpdateSigningKey.cs  64  18  SparkleDotNET Tools
Warning 21  The variable 'e' is declared but never used D:\bt\KNFoundation\KNFoundation\KNPropertyListSerialization.cs  60  32  KNFoundation
```

**Comment by angitbit** [comment]
try build clean

**Comment by richard-bt** [comment]
What I ended up doing was explicitly target "Release | x86" for all of the solutions and rebuilt. These solutions seem to be all screwed up for knowing what needs to be built and in what order, as well as reaching for dependencies with `../../`. This all grosses me out.

**Comment by angitbit** [comment]
mixed platforms seems to be default for me; i use debug

**Comment by richard-bt** [comment]
I've updated this PR to switch the "Test Application" from creating/signing with DSA to RSA PKCS1 with SHA256. 

Next step is to update the core SparkleDotNET library to perform signature verification with RSA PKCS1 with SHA256.

**Comment by angitbit** [comment]
can you revert icon changes?

**Comment by richard-bt** [comment]
Thanks for the reminder, I'll revert that commit at some point in the future. My current working environment is without backdated dependencies.

**Comment by richard-bt** [comment]
I'm going to close this PR and re-open another targeting master with my signature changes.

**Pull request closed without merging**
