### PR TITLE
build tool from source

### PR DESCRIPTION
**Pull request by angitbit**
@richard-bt 
get https://github.com/iKenndac/KNControlsWinForms
https://github.com/iKenndac/KNFoundation
backdate to
https://github.com/iKenndac/KNFoundation/commit/156c58a7066c62e23a2638805317c9ed2ec68775

### CODE REVIEW

**Comment by angitbit** [comment]
@twilmoth

**Comment by richard-bt** [comment]
Thanks An!

I was getting some build errors having to do with icons. I've created a PR removing icons targeting your `anbuild` branch. If it looks good, merge https://github.com/bt-browser/SparkleDotNET/pull/3 so that the changes become a part of this PR. 

I can build the "SparkleDotNET Tools" executable and verify the export private key, export public key, and sign file functionality.

**Comment by angitbit** [comment]
replaced by dotnet-tools pull

**Comment by angitbit** [comment]
reopened

**Pull request closed without merging**
